import { analyzeRequirements, analysisToCsv, analysisToMarkdown } from './lib/analyzer.js';

const SAMPLE = {
  projectName: '受注管理システム刷新', releaseDate: '2026-10-31',
  oldText: `1. 注文登録画面で顧客名、商品、数量を入力する。
2. 登録済み注文は担当者のみ編集できる。
3. 注文確定時に在庫数を更新する。
4. 注文一覧は受注日と担当者で検索できる。
5. 注文確定後は顧客へ受付メールを送信する。
6. 処理結果は画面に表示する。
7. 注文データは5年間保存する。
8. システム管理者は月次の受注件数をCSV出力できる。`,
  newText: `1. 注文登録画面で顧客名、商品、数量、希望納期を入力する。希望納期は必須とする。
2. 登録済み注文は担当者と管理者が編集でき、変更前後の値を履歴として保存する。
3. 注文確定時に在庫数を更新し、在庫不足の場合はSlackへ即時通知する。
4. 注文一覧は受注日、担当者、商品、ステータスで検索でき、検索条件を保存できる。
5. 注文確定後は顧客へ受付メールを送信し、送信失敗時は3回まで自動再送する。
6. 一度確定した注文の削除は管理者のみ実行でき、操作内容を監査ログに保持する。
7. 処理結果は通常時3秒以内、ピーク時5秒以内に画面へ表示する。
8. 注文データと変更履歴は7年間保存する。
9. 毎日2時に未確定注文を抽出し、担当者へリマインド通知する。
10. システム管理者は月次の受注件数・金額・キャンセル率をCSV出力できる。`
};
const META = { overview:['CHANGE INTELLIGENCE','影響分析ダッシュボード'], input:['REQUIREMENT INPUT','要件入力'], changes:['CHANGE DETECTION','変更点の確認'], impact:['IMPACT NETWORK','変更影響マップ'], tasks:['ACTION PLAN','対応タスク'], trace:['TRACEABILITY','追跡・レポート出力'] };
const TYPE = { added:'追加', modified:'変更', removed:'削除' }, SEVERITY = { high:'高リスク', medium:'要注意', low:'低リスク' };
const STORE = 'requirements-impact-analyzer:v1', TASK_STORE = 'requirements-impact-analyzer:tasks:v1', THEME_STORE = 'requirements-impact-analyzer:theme';
const state = { analysis:null, view:'overview', selected:null, completed:new Set(), timer:null };
const $ = (selector, root=document) => root.querySelector(selector), $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#icon-${name}"></use></svg>`;
const esc = (value='') => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

function storedInput(){ try { const value=JSON.parse(localStorage.getItem(STORE)); return value?.oldText && value?.newText ? value : SAMPLE; } catch { return SAMPLE; } }
function populate(value){ $('#projectName').value=value.projectName||''; $('#releaseDate').value=value.releaseDate||''; $('#oldText').value=value.oldText||''; $('#newText').value=value.newText||''; counts(); }
function counts(){ for(const prefix of ['old','new']){ const text=$(`#${prefix}Text`).value; $(`#${prefix}LineCount`).textContent=`${text.split(/\n+/).filter(line=>line.trim()).length}項目`; $(`#${prefix}CharCount`).textContent=`${text.length.toLocaleString('ja-JP')}文字`; } }
function setView(view){ if(!META[view]) return; state.view=view; $$('[data-view-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.viewPanel===view)); $$('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view)); const [eyebrow,title]=META[view]; $('#pageEyebrow').textContent=eyebrow; $('#pageTitle').textContent=title; document.body.classList.remove('sidebar-open'); try{history.replaceState(null,'',`${location.pathname}?view=${view}`);}catch{} scrollTo({top:0}); }
function analyze({navigate=false,persist=true}={}){ const input={projectName:$('#projectName').value.trim()||'名称未設定プロジェクト',releaseDate:$('#releaseDate').value,oldText:$('#oldText').value,newText:$('#newText').value}; if(!input.oldText.trim()&&!input.newText.trim()){toast('要件を入力してください','info');return;} state.analysis=analyzeRequirements(input); state.selected=state.analysis.impactSummary[0]?.id||null; if(persist)localStorage.setItem(STORE,JSON.stringify(input)); renderAll(); $('#projectStatus').textContent=`${state.analysis.summary.changeCount}件の変更を分析済み`; if(navigate){setView('overview');toast('影響範囲の分析が完了しました');} }

function renderAll(){ const a=state.analysis;if(!a)return; $('#navChangeCount').textContent=a.summary.changeCount; $('#navTaskCount').textContent=a.summary.taskCount; $('#heroProjectName').textContent=a.meta.projectName; $('#overallRiskScore').textContent=a.summary.overallRisk.score; $('#overallRiskLabel').textContent=a.summary.overallRisk.label; metrics(); radar(); recommendations(); topChanges(); changeSummary(); changes(); impactMap(); impactRanking(); selectedImpact(); tasks(); trace(); }
function metrics(){ const s=state.analysis.summary, values=[['検出した変更',s.changeCount,'件','diff','primary',s.changeCount*9],['高リスク変更',s.highRiskCount,'件','shield','red',s.highRiskCount*25],['影響領域',s.impactedAreaCount,'領域','network','cyan',s.impactedAreaCount*10],['概算対応工数',s.totalHours,'時間','tasks','green',s.totalHours/2]]; $('#metricGrid').innerHTML=values.map(([label,value,unit,ic,tone,bar])=>`<article class="metric-card"><div class="metric-copy"><span>${label}</span><strong>${value}</strong><small>${unit}</small></div><span class="metric-icon ${tone}">${icon(ic)}</span><div class="metric-trend"><span style="width:${Math.min(100,bar)}%"></span></div></article>`).join(''); }
function point(index,value,count,radius=96){ const angle=-Math.PI/2+Math.PI*2*index/count; return [160+Math.cos(angle)*radius*value/100,138+Math.sin(angle)*radius*value/100]; }
const pointText=values=>values.map(([x,y])=>`${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
function radar(){ const dims=state.analysis.riskDimensions,count=dims.length; const grids=[25,50,75,100].map(level=>`<polygon class="radar-grid" points="${pointText(dims.map((_,i)=>point(i,level,count)))}"></polygon>`).join(''); const axes=dims.map((_,i)=>{const[x,y]=point(i,100,count);return`<line class="radar-axis" x1="160" y1="138" x2="${x}" y2="${y}"></line>`}).join(''); const shape=dims.map((item,i)=>point(i,item.value,count)); const dots=shape.map(([x,y])=>`<circle class="radar-point" cx="${x}" cy="${y}" r="4"></circle>`).join(''); const labels=dims.map((item,i)=>{const[x,y]=point(i,100,count,121);return`<text class="radar-label" x="${x}" y="${y}">${esc(item.label)}</text>`}).join(''); $('#riskRadar').innerHTML=`${grids}${axes}<polygon class="radar-shape" points="${pointText(shape)}"></polygon>${dots}${labels}`; $('#riskLegend').innerHTML=dims.map(item=>`<div class="risk-legend-row"><span>${esc(item.label)}</span><strong>${item.value}</strong><div class="risk-bar"><i style="width:${item.value}%"></i></div></div>`).join(''); const risk=state.analysis.summary.overallRisk; $('#riskBadge').textContent=`${risk.label} ${risk.score}`; }
function recommendations(){ $('#recommendationList').innerHTML=state.analysis.recommendations.map(item=>`<li>${esc(item)}</li>`).join(''); }
function topChanges(){ const list=[...state.analysis.changes].sort((a,b)=>b.risk.score-a.risk.score).slice(0,5); $('#topChangeList').innerHTML=list.length?list.map(change=>`<button class="top-change-item" type="button" data-change-jump="${change.id}"><span class="change-id">${change.id}</span><span class="change-summary">${esc(change.summary)}</span><span class="impact-mini-list">${change.impacts.slice(0,3).map(impact=>`<span class="impact-mini">${esc(impact.shortLabel)}</span>`).join('')}</span><span class="risk-score-mini ${change.risk.severity}">${change.risk.score}</span></button>`).join(''):'<div class="selected-impact-empty">変更点はありません。</div>'; $$('[data-change-jump]').forEach(button=>button.onclick=()=>{setView('changes');requestAnimationFrame(()=>document.getElementById(button.dataset.changeJump)?.scrollIntoView({behavior:'smooth',block:'center'}));}); }
function changeSummary(){ const s=state.analysis.summary, values=[['added','追加',s.typeCounts.added],['modified','変更',s.typeCounts.modified],['removed','削除',s.typeCounts.removed],['high','高リスク',s.highRiskCount]]; $('#changeSummaryStrip').innerHTML=values.map(([tone,label,value])=>`<div class="summary-chip ${tone}"><span>${label}</span><strong>${value}</strong></div>`).join(''); $('#changesDescription').textContent=`${state.analysis.meta.projectName}から${s.changeCount}件の変更を検出しました。`; }
function changes(){ const query=($('#changeSearch')?.value||'').toLowerCase(), filter=$('#severityFilter')?.value||'all'; const list=state.analysis.changes.filter(change=>{const text=`${change.id} ${change.before} ${change.after} ${change.impacts.map(item=>item.label).join(' ')}`.toLowerCase();return(filter==='all'||change.risk.severity===filter)&&(!query||text.includes(query));}); $('#changeList').innerHTML=list.map(change=>{const words=[...new Set([...change.risk.highHits,...change.risk.mediumHits,...change.impacts.flatMap(impact=>impact.hits)])].slice(0,8);return`<article class="change-card" id="${change.id}"><div class="change-card-head"><span class="change-id">${change.id}</span><span class="change-type-badge ${change.type}">${TYPE[change.type]}</span><span class="change-card-title">${esc(change.summary)}</span><span class="severity-badge ${change.risk.severity}">${SEVERITY[change.risk.severity]}</span><span class="change-score">${change.risk.score}</span></div><div class="change-card-body"><div class="diff-grid"><div class="diff-block before"><small>BEFORE</small><p class="${change.before?'':'empty-diff'}">${change.before?esc(change.before):'（新規追加）'}</p></div><div class="diff-arrow">${icon('arrow')}</div><div class="diff-block after"><small>AFTER</small><p class="${change.after?'':'empty-diff'}">${change.after?esc(change.after):'（削除）'}</p></div></div><div class="change-impact-row"><div class="impact-tags">${change.impacts.map(impact=>`<span class="impact-tag">${esc(impact.label)} ${impact.confidence}%</span>`).join('')}</div><span class="keyword-hits">根拠語: ${words.length?words.map(esc).join(' / '):'文脈類似度'}</span></div></div></article>`}).join(''); $('#changeEmptyState').hidden=Boolean(list.length); }
const severityFor=value=>value>=68?'high':value>=40?'medium':'low';
function impactMap(){ const items=state.analysis.impactSummary,map=$('#impactMap'); if(!items.length){map.innerHTML='<div class="selected-impact-empty">影響領域はありません。</div>';return;} const positions=items.map((_,index)=>{const angle=-Math.PI/2+Math.PI*2*index/items.length;return{x:50+Math.cos(angle)*37,y:50+Math.sin(angle)*37}}); const lines=positions.map(position=>`<line class="map-line-glow" x1="50%" y1="50%" x2="${position.x}%" y2="${position.y}%"></line><line class="map-line" x1="50%" y1="50%" x2="${position.x}%" y2="${position.y}%"></line>`).join(''); const nodes=items.map((item,index)=>`<button class="map-node ${state.selected===item.id?'active':''}" type="button" data-impact="${item.id}" style="left:${positions[index].x}%;top:${positions[index].y}%"><i class="${severityFor(item.risk)}"></i><strong>${esc(item.label)}</strong><span>${item.count}件の変更</span><em class="node-score">影響度 ${Math.round(item.strength)}</em></button>`).join(''); map.innerHTML=`<svg class="map-lines" aria-hidden="true">${lines}</svg><div class="map-center"><span>CHANGE SET</span><strong>${state.analysis.summary.changeCount}</strong><small>検出した変更</small></div>${nodes}`; $$('[data-impact]',map).forEach(button=>button.onclick=()=>{state.selected=button.dataset.impact;impactMap();selectedImpact();}); }
function impactRanking(){ $('#impactRanking').innerHTML=state.analysis.impactSummary.slice(0,7).map((item,index)=>`<button class="impact-rank-row" type="button" data-rank="${item.id}"><span class="rank-number">${index+1}</span><span class="impact-rank-copy"><span class="impact-rank-label"><span>${esc(item.label)}</span><small>${item.count} changes</small></span><span class="impact-rank-bar"><span style="width:${item.strength}%"></span></span></span><span class="impact-rank-score">${Math.round(item.strength)}</span></button>`).join(''); $$('[data-rank]').forEach(button=>button.onclick=()=>{state.selected=button.dataset.rank;impactMap();selectedImpact();}); }
function selectedImpact(){ const item=state.analysis.impactSummary.find(impact=>impact.id===state.selected); if(!item){$('#selectedImpactContent').innerHTML='<div class="selected-impact-empty">領域を選択してください。</div>';return;} $('#selectedImpactTitle').textContent=item.label; const related=state.analysis.tasks.filter(task=>task.impactId===item.id); $('#selectedImpactContent').innerHTML=`<div class="selected-impact-stats"><div class="selected-stat"><strong>${item.count}</strong><span>関連変更</span></div><div class="selected-stat"><strong>${item.risk}</strong><span>平均リスク</span></div><div class="selected-stat"><strong>${related.reduce((sum,task)=>sum+task.estimateHours,0)}h</strong><span>概算工数</span></div></div><div class="selected-section"><h4>関連する変更</h4><ul>${item.changeIds.slice(0,5).map(id=>`<li><strong>${id}</strong> ${esc(state.analysis.changes.find(change=>change.id===id)?.summary||'')}</li>`).join('')}</ul></div><div class="selected-section"><h4>更新対象の成果物</h4><ul>${item.artifacts.map(value=>`<li>${esc(value)}</li>`).join('')}</ul></div><div class="selected-section"><h4>重点テスト</h4><ul>${item.tests.map(value=>`<li>${esc(value)}</li>`).join('')}</ul></div>`; }
function tasks(){ const list=state.analysis.tasks, completed=list.filter(task=>state.completed.has(task.id)).length, percent=list.length?Math.round(completed/list.length*100):0; $('#taskDoneCount').textContent=completed;$('#taskTotalCount').textContent=list.length;$('#taskProgressPercent').textContent=`${percent}%`;$('#taskProgressRing').style.setProperty('--progress',`${percent}%`);$('#taskProgressBar').style.width=`${percent}%`;$('#taskEstimateText').textContent=`残り約${list.filter(task=>!state.completed.has(task.id)).reduce((sum,task)=>sum+task.estimateHours,0)}時間 / 全体${state.analysis.summary.estimatedDays}人日相当`; const groups=[['high','高リスク'],['medium','要注意'],['low','低リスク']]; $('#taskBoard').innerHTML=groups.map(([severity,label])=>{const group=list.filter(task=>task.priority===severity);return`<section class="task-column ${severity}"><div class="task-column-head"><h3><i></i>${label}</h3><span>${group.length}</span></div><div class="task-card-list">${group.length?group.map(task=>`<article class="task-card ${state.completed.has(task.id)?'completed':''}"><div class="task-card-top"><span class="task-card-id">${task.id} • ${task.changeId}</span><button class="task-check ${state.completed.has(task.id)?'checked':''}" type="button" data-task="${task.id}">${icon('check')}</button></div><h4 class="task-card-title">${esc(task.title)}</h4><div class="task-meta"><span>${esc(task.owner)}</span><span>${task.estimateHours}h</span><span>${esc(task.acceptance)}</span></div><p class="task-deliverable">成果物：${esc(task.deliverable)}</p></article>`).join(''):'<div class="selected-impact-empty">該当タスクなし</div>'}</div></section>`}).join(''); $$('[data-task]').forEach(button=>button.onclick=()=>{state.completed.has(button.dataset.task)?state.completed.delete(button.dataset.task):state.completed.add(button.dataset.task);localStorage.setItem(TASK_STORE,JSON.stringify([...state.completed]));tasks();}); }
function trace(){ const a=state.analysis, links=a.traceability.flatMap(row=>row.links.map(link=>({row,...link}))); $('#traceLinkCount').textContent=`${links.length} links`; $('#traceTableBody').innerHTML=links.map(({row,...link})=>`<tr><td><strong>${row.changeId}</strong></td><td><span class="table-risk ${row.severity}">${SEVERITY[row.severity]}</span></td><td>${esc(link.impactLabel)}</td><td>${esc(link.artifact)}</td><td><strong>${esc(link.testCase)}</strong></td><td>${esc(link.owner)}</td></tr>`).join(''); $('#reportSummaryCard').innerHTML=`<div class="report-title-block"><p class="section-label">EXECUTIVE SUMMARY</p><h3>${esc(a.meta.projectName)}</h3><p>${new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(a.meta.analyzedAt))}時点の変更影響分析。総合判定は「${a.summary.overallRisk.label}」です。</p></div><div class="report-stat"><strong>${a.summary.overallRisk.score}</strong><span>総合リスク</span></div><div class="report-stat"><strong>${a.summary.changeCount}</strong><span>変更件数</span></div><div class="report-stat"><strong>${a.summary.totalHours}h</strong><span>概算工数</span></div>`; $('#reportPreview').textContent=analysisToMarkdown(a); }
function download(name,content,type){ const url=URL.createObjectURL(new Blob([content],{type})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);toast(`${name}を出力しました`); }
const slug=value=>value.normalize('NFKC').toLowerCase().replace(/[^a-z0-9\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]+/gu,'-').replace(/^-|-$/g,'')||'impact-analysis';
const exportCsv=()=>download(`${slug(state.analysis.meta.projectName)}-impact.csv`,analysisToCsv(state.analysis),'text/csv;charset=utf-8');
function toast(message,type='success'){ $('#toastMessage').textContent=message; $('use',$('#toast')).setAttribute('href',type==='info'?'#icon-info':'#icon-check'); $('#toast').classList.add('show'); clearTimeout(state.timer);state.timer=setTimeout(()=>$('#toast').classList.remove('show'),2400); }
async function readFile(input,textarea){ const file=input.files?.[0];if(!file)return;if(file.size>2_000_000){toast('2MB以下のファイルを選択してください','info');return;}textarea.value=await file.text();counts();toast(`${file.name}を読み込みました`); }
function bind(){ $$('.nav-item').forEach(button=>button.onclick=()=>setView(button.dataset.view)); $$('[data-jump]').forEach(button=>button.onclick=()=>setView(button.dataset.jump)); $('#analysisForm').onsubmit=event=>{event.preventDefault();analyze({navigate:true});}; $('#loadSampleButton').onclick=()=>{populate(SAMPLE);analyze();toast('サンプル要件を読み込みました');}; $('#resetButton').onclick=()=>{populate({});toast('入力欄をクリアしました','info');}; for(const id of ['oldText','newText'])$(`#${id}`).oninput=counts; $('#oldFile').onchange=()=>readFile($('#oldFile'),$('#oldText'));$('#newFile').onchange=()=>readFile($('#newFile'),$('#newText'));$('#changeSearch').oninput=changes;$('#severityFilter').onchange=changes;$('#downloadTasksButton').onclick=exportCsv;$('#exportCsvButton').onclick=exportCsv;$('#exportMarkdownButton').onclick=()=>download(`${slug(state.analysis.meta.projectName)}-impact-report.md`,analysisToMarkdown(state.analysis),'text/markdown;charset=utf-8');$('#exportJsonButton').onclick=()=>download(`${slug(state.analysis.meta.projectName)}-impact.json`,JSON.stringify(state.analysis,null,2),'application/json;charset=utf-8');$('#copyReportButton').onclick=async()=>{try{await navigator.clipboard.writeText(analysisToMarkdown(state.analysis));toast('レポートをコピーしました');}catch{toast('コピーできませんでした','info');}};$('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem(THEME_STORE,next);radar();};$('#mobileMenu').onclick=()=>document.body.classList.toggle('sidebar-open');$('#sidebarScrim').onclick=()=>document.body.classList.remove('sidebar-open');addEventListener('keydown',event=>{if(event.key==='Escape')document.body.classList.remove('sidebar-open');if((event.metaKey||event.ctrlKey)&&event.key==='Enter'&&state.view==='input'){event.preventDefault();analyze({navigate:true});}}); }
function init(){ const theme=localStorage.getItem(THEME_STORE)||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');document.documentElement.dataset.theme=theme;try{state.completed=new Set(JSON.parse(localStorage.getItem(TASK_STORE))||[]);}catch{}populate(storedInput());bind();analyze({persist:false});const requested=new URLSearchParams(location.search).get('view');setView(META[requested]?requested:'overview');if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{})); }
init();
